name: "build"
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Compile libiosexec
          run: make all
        - name: Run tests
          run: make test
