name: Build

on:
  push:
    paths-ignore:
      - 'LICENSE'  
      - '**/*.md'  
      - '**/*.txt'
      - '.gitignore'  
  pull_request:
    paths-ignore:
      - 'LICENSE'  
      - '**/*.md'  
      - '**/*.txt'  
      - '.gitignore'  

env:
  LIBIOSEXEC_CFLAGS: -isysroot $(xcrun --sdk macosx --show-sdk-path)

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile libiosexec
        run: |
          make all CFLAGS="${{ env.LIBIOSEXEC_CFLAGS }}"
      - name: Run tests
        run: |
          make test CFLAGS="${{ env.LIBIOSEXEC_CFLAGS }}"
