name: "build"
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Compile libiosexec
          run: make all CFLAGS="-isysroot $(xcrun --sdk macosx --show-sdk-path)"
        - name: Run tests
          run: make test
